apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: hocs-management-ui
  name: hocs-management-ui
spec:
  maxReplicas: 2
  minReplicas: {{.REPLICAS}}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hocs-management-ui
  targetCPUUtilizationPercentage: 24
