---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/enabled: "true"
    ingress.kubernetes.io/secure-backends: "true"
    ingress.kubernetes.io/backend-protocol: "HTTPS"
    kubernetes.io/ingress.class: nginx-external
    ingress.kubernetes.io/proxy-buffer-size: 128k
    ingress.kubernetes.io/server-snippets: |
      client_header_buffer_size     8k;
      large_client_header_buffers   4 128k;
  labels:
    cert-manager.io/solver: http01
  name: hocs-management-ui
spec:
  rules:
  - host: {{.DOMAIN_NAME}}
    http:
      paths:
      - backend:
          serviceName: hocs-management-ui
          servicePort: 443
        path: /

  tls:
  - hosts:
    - {{.DOMAIN_NAME}}
    secretName: hocs-management-ui-external-tls
